var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/exports/route.js")
R.c("server/chunks/[root-of-the-server]__13qv7i3._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/definitions_ts_0z1von.._.js")
R.c("server/chunks/lib_supabase_admin_ts_02-3bsq._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0_t5ti~._.js")
R.c("server/chunks/_0zh1y.d._.js")
R.c("server/chunks/_next-internal_server_app_api_exports_route_actions_0qij0ws.js")
R.m(93080)
module.exports=R.m(93080).exports
