var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/tools/route.js")
R.c("server/chunks/_0ehpp~p._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/[root-of-the-server]__0cw8984._.js")
R.c("server/chunks/lib_env_ts_0~mjrc4._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_tools_route_actions_0cszc2o.js")
R.m(52258)
module.exports=R.m(52258).exports
