var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/exports/route.js")
R.c("server/chunks/[root-of-the-server]__0fk9u8c._.js")
R.c("server/chunks/lib_env_ts_0~mjrc4._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_0_t5ti~._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/_next-internal_server_app_api_exports_route_actions_0qij0ws.js")
R.m(93080)
module.exports=R.m(93080).exports
