// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/api-cost" | "/admin/billing" | "/admin/payments" | "/admin/settings" | "/admin/subscriptions" | "/admin/tools" | "/admin/users" | "/admin/verify" | "/auth/callback" | "/billing" | "/blog" | "/blog/[slug]" | "/blog/category/[slug]" | "/categories/[slug]" | "/compare/[slug]" | "/contact" | "/dashboard" | "/dashboard/tools" | "/history" | "/industries/[slug]" | "/login" | "/outputs/[slug]" | "/pricing" | "/privacy" | "/refund" | "/register" | "/settings" | "/terms" | "/tools" | "/tools/[slug]" | "/use-cases/[slug]"
type AppRouteHandlerRoutes = "/api/admin/tool-pricing" | "/api/admin/users" | "/api/admin/verify" | "/api/analytics/pageview" | "/api/billing/checkout" | "/api/billing/subscription" | "/api/billing/verify" | "/api/billing/webhook" | "/api/exports" | "/api/extension/generate" | "/api/extension/session" | "/api/og" | "/api/outputs/publish" | "/api/razorpay/webhook" | "/api/register" | "/api/tools"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/api-cost": {}
  "/admin/billing": {}
  "/admin/payments": {}
  "/admin/settings": {}
  "/admin/subscriptions": {}
  "/admin/tools": {}
  "/admin/users": {}
  "/admin/verify": {}
  "/api/admin/tool-pricing": {}
  "/api/admin/users": {}
  "/api/admin/verify": {}
  "/api/analytics/pageview": {}
  "/api/billing/checkout": {}
  "/api/billing/subscription": {}
  "/api/billing/verify": {}
  "/api/billing/webhook": {}
  "/api/exports": {}
  "/api/extension/generate": {}
  "/api/extension/session": {}
  "/api/og": {}
  "/api/outputs/publish": {}
  "/api/razorpay/webhook": {}
  "/api/register": {}
  "/api/tools": {}
  "/auth/callback": {}
  "/billing": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/category/[slug]": { "slug": string; }
  "/categories/[slug]": { "slug": string; }
  "/compare/[slug]": { "slug": string; }
  "/contact": {}
  "/dashboard": {}
  "/dashboard/tools": {}
  "/history": {}
  "/industries/[slug]": { "slug": string; }
  "/login": {}
  "/outputs/[slug]": { "slug": string; }
  "/pricing": {}
  "/privacy": {}
  "/refund": {}
  "/register": {}
  "/settings": {}
  "/terms": {}
  "/tools": {}
  "/tools/[slug]": { "slug": string; }
  "/use-cases/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
