import { z } from "zod";
import type { ToolDefinition } from "@/types/tools";
import { buildLegacyToolPrompt } from "@/services/ai/prompt-system";

function parseJsonResponse<T>(response: string): T {
  const normalized = response.trim().replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```$/i, "").trim();
  return JSON.parse(normalized) as T;
}

const seoArticleInput = z.object({
  targetKeyword: z.string().min(2),
  audience: z.string().min(2),
  tone: z.string().min(2),
  articleLength: z.string().min(2),
  niche: z.string().min(2),
  competitorUrl: z.string().url().optional().or(z.literal("")),
});

const seoArticleOutput = z.object({
  seoTitle: z.string(),
  metaDescription: z.string(),
  searchIntent: z.string(),
  keywordClusters: z.array(z.string()),
  articleOutline: z.array(z.string()),
  fullArticle: z.string(),
  faqSection: z.array(z.object({ question: z.string(), answer: z.string() })),
  internalLinkSuggestions: z.array(z.string()),
});

const adCopyInput = z.object({
  productService: z.string().min(2),
  audience: z.string().min(2),
  platform: z.string().min(2),
  offer: z.string().min(2),
  tone: z.string().min(2),
});

const adCopyOutput = z.object({
  headlines: z.array(z.string()).length(10),
  primaryTexts: z.array(z.string()).length(5),
  ctaOptions: z.array(z.string()).length(5),
  adVariations: z.array(z.object({ headline: z.string(), body: z.string(), cta: z.string() })).length(3),
  angleExplanation: z.array(z.string()),
});

const personaInput = z.object({
  businessDescription: z.string().min(10),
  niche: z.string().min(2),
  targetMarket: z.string().min(2),
  priceRange: z.string().min(2),
});

const personaOutput = z.object({
  buyerPersona: z.string(),
  demographics: z.array(z.string()),
  painPoints: z.array(z.string()),
  goals: z.array(z.string()),
  objections: z.array(z.string()),
  buyingTriggers: z.array(z.string()),
  contentIdeas: z.array(z.string()),
  messagingAngles: z.array(z.string()),
});

const bgInput = z.object({ imageName: z.string().min(1, "Image is required") });
const bgOutput = z.object({ status: z.string(), message: z.string() });

const landingInput = z.object({
  productName: z.string().min(2),
  targetAudience: z.string().min(2),
  coreProblem: z.string().min(2),
  mainBenefit: z.string().min(2),
  tone: z.string().min(2),
});

const landingOutput = z.object({
  heroHeadline: z.string(),
  subheadline: z.string(),
  ctaButtons: z.array(z.string()),
  problemSection: z.array(z.string()),
  solutionSection: z.array(z.string()),
  benefits: z.array(z.string()),
  testimonialsSuggestions: z.array(z.string()),
  faq: z.array(z.object({ question: z.string(), answer: z.string() })),
  finalCta: z.string(),
});

const browserContextInput = z.object({
  selectedText: z.string().min(4),
  pageTitle: z.string().optional().default(""),
  pageUrl: z.string().url().optional().or(z.literal("")),
  pageContext: z.string().optional().default(""),
  tone: z.string().optional().default("Professional"),
  audience: z.string().optional().default("General audience"),
  objective: z.string().optional().default(""),
  platform: z.string().optional().default("Web"),
});

const browserTextOutput = z.object({
  result: z.string(),
  title: z.string(),
  suggestions: z.array(z.string()),
});

const browserSeoOutput = z.object({
  result: z.string(),
  title: z.string(),
  suggestions: z.array(z.string()),
});

const browserAdCopyOutput = z.object({
  result: z.string(),
  title: z.string(),
  suggestions: z.array(z.string()),
});

export const toolRegistry: Record<string, ToolDefinition> = {
  "seo-article-generator": {
    id: "seo-article-generator",
    metadata: {
      name: "AI SEO Article Generator",
      description: "Long-form SEO article system with strategy layers.",
      category: "SEO",
      icon: "📝",
      tagline: "Research-backed article production with SERP-ready structure.",
      estimatedTimeSeconds: 85,
      outputType: "article",
      tags: ["Content Engine", "SERP Strategy", "SaaS", "Growth"],
      featured: true,
      trending: true,
      availability: "active",
      visibility: "public",
    },
    fields: [
      { name: "targetKeyword", label: "Target Keyword", type: "text", placeholder: "best crm software for startups", helperText: "Use one primary keyword with clear search intent.", required: true },
      { name: "audience", label: "Audience", type: "text", placeholder: "B2B SaaS founders", helperText: "Be specific about role, industry, or sophistication level.", required: true },
      { name: "tone", label: "Tone", type: "select", helperText: "Choose the editorial voice for the draft.", required: true, options: [{ label: "Professional", value: "Professional" }, { label: "Authoritative", value: "Authoritative" }, { label: "Friendly", value: "Friendly" }] },
      { name: "articleLength", label: "Article Length", type: "select", helperText: "Longer outputs add more topical depth and FAQ coverage.", required: true, options: [{ label: "1200-1500 words", value: "1200-1500 words" }, { label: "1500-2000 words", value: "1500-2000 words" }, { label: "2000+ words", value: "2000+ words" }] },
      { name: "niche", label: "Business / Niche", type: "text", placeholder: "SaaS sales enablement", helperText: "Give the model business context so examples feel relevant.", required: true },
      { name: "competitorUrl", label: "Competitor URL (optional)", type: "text", placeholder: "https://example.com/article", helperText: "Optional reference URL for positioning and coverage depth." },
    ],
    examples: [
      { title: "B2B SaaS SEO pillar", description: "Create a high-intent article for a software comparison keyword with FAQ coverage." },
      { title: "Agency client draft", description: "Build an export-ready article outline and full draft for a client niche." },
    ],
    presets: [
      {
        label: "SaaS comparison article",
        description: "High-intent bottom-funnel SEO article for software buyers.",
        values: {
          targetKeyword: "best crm software for startups",
          audience: "B2B SaaS founders",
          tone: "Authoritative",
          articleLength: "2000+ words",
          niche: "Startup sales operations",
          competitorUrl: "",
        },
      },
      {
        label: "Educational blog post",
        description: "Top-of-funnel article for thought leadership and discoverability.",
        values: {
          targetKeyword: "how to improve onboarding emails",
          audience: "Lifecycle marketers at SaaS companies",
          tone: "Professional",
          articleLength: "1500-2000 words",
          niche: "Email automation software",
          competitorUrl: "",
        },
      },
    ],
    inputSchema: seoArticleInput,
    outputSchema: seoArticleOutput,
    creditCost: 10,
    usageClass: "heavy",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["md", "pdf", "txt", "json"],
    promptTemplate: (i: z.infer<typeof seoArticleInput>) => buildLegacyToolPrompt("seo-article-generator", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof seoArticleOutput>>(r),
  },
  "ad-copy-generator": {
    id: "ad-copy-generator",
    metadata: {
      name: "AI Ad Copy Generator",
      description: "Multi-angle ad pack built for paid campaigns.",
      category: "Marketing",
      icon: "📣",
      tagline: "Launch-ready paid creative with angles, CTAs, and variation cards.",
      estimatedTimeSeconds: 35,
      outputType: "ad-copy",
      tags: ["Paid Ads", "Social Media", "Performance", "Offers"],
      featured: true,
      trending: true,
      availability: "active",
      visibility: "public",
    },
    fields: [
      { name: "productService", label: "Product / Service", type: "text", placeholder: "AI meeting assistant", helperText: "Use the exact product or offer you’re promoting.", required: true },
      { name: "audience", label: "Audience", type: "text", placeholder: "Remote startup teams", helperText: "Audience clarity improves hooks and objections.", required: true },
      { name: "platform", label: "Platform", type: "select", helperText: "Channel-specific outputs adapt tone and density.", required: true, options: [{ label: "Meta", value: "Meta" }, { label: "Google", value: "Google" }, { label: "LinkedIn", value: "LinkedIn" }, { label: "X", value: "X" }] },
      { name: "offer", label: "Offer", type: "text", placeholder: "14-day starter access", helperText: "State the promo, lead magnet, or call-to-action clearly.", required: true },
      { name: "tone", label: "Tone", type: "select", helperText: "Controls the persuasion style of the campaign pack.", required: true, options: [{ label: "Bold", value: "Bold" }, { label: "Professional", value: "Professional" }, { label: "Conversational", value: "Conversational" }] },
    ],
    examples: [
      { title: "Meta launch campaign", description: "Generate scroll-stopping hooks, primary texts, and CTA combinations for a promo campaign." },
      { title: "LinkedIn demand gen", description: "Create more polished, ROI-oriented ad copy for B2B decision makers." },
    ],
    presets: [
      {
        label: "SaaS trial campaign",
        description: "Paid ad pack for direct acquisition campaigns.",
        values: {
          productService: "AI meeting assistant",
          audience: "Remote startup teams",
          platform: "Meta",
          offer: "Book a strategy demo",
          tone: "Bold",
        },
      },
      {
        label: "B2B lead gen",
        description: "Professional copy for higher-intent LinkedIn acquisition.",
        values: {
          productService: "Revenue analytics dashboard",
          audience: "VPs of Sales at mid-market SaaS companies",
          platform: "LinkedIn",
          offer: "Book a strategy demo",
          tone: "Professional",
        },
      },
    ],
    inputSchema: adCopyInput,
    outputSchema: adCopyOutput,
    creditCost: 2,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof adCopyInput>) => buildLegacyToolPrompt("ad-copy-generator", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof adCopyOutput>>(r),
  },
  "customer-persona-builder": {
    id: "customer-persona-builder",
    metadata: {
      name: "AI Customer Persona Builder",
      description: "Buyer-intelligence profile for conversion messaging.",
      category: "Research",
      icon: "🧠",
      tagline: "Transform rough business context into actionable audience intelligence.",
      estimatedTimeSeconds: 52,
      outputType: "persona",
      tags: ["Audience Research", "Positioning", "Messaging", "Personas"],
      featured: false,
      trending: true,
      availability: "active",
      visibility: "public",
    },
    fields: [
      { name: "businessDescription", label: "Website / Business Description", type: "textarea", placeholder: "We sell cybersecurity training for SMB teams...", helperText: "Summarize the offer, buyer context, and why customers pay.", required: true },
      { name: "niche", label: "Niche", type: "text", placeholder: "Cybersecurity education", helperText: "Industry context sharpens the persona profile.", required: true },
      { name: "targetMarket", label: "Target Market", type: "text", placeholder: "US-based SMB owners", helperText: "Mention geography, company type, or role if possible.", required: true },
      { name: "priceRange", label: "Price Range", type: "text", placeholder: "₹2,499 - ₹9,999", helperText: "Pricing context helps infer urgency, objections, and perceived value.", required: true },
    ],
    examples: [
      { title: "Founder positioning", description: "Use persona insights to refine your ICP, objections, and messaging angles." },
      { title: "Campaign planning", description: "Generate pain points and buying triggers to feed landing pages and ads." },
    ],
    presets: [
      {
        label: "B2B training persona",
        description: "Audience profile for a mid-ticket education product.",
        values: {
          businessDescription: "We provide cybersecurity training for small and mid-sized business teams that need compliance-friendly employee education.",
          niche: "Cybersecurity education",
          targetMarket: "US-based SMB owners and operations managers",
          priceRange: "₹2,499 - ₹9,999",
        },
      },
      {
        label: "SaaS onboarding persona",
        description: "Research starter for onboarding and lifecycle messaging.",
        values: {
          businessDescription: "We sell workflow automation software for startups that want to reduce manual operations and onboard clients faster.",
          niche: "Workflow automation SaaS",
          targetMarket: "Operations leads at seed to Series B startups",
          priceRange: "$49 - $299 per month",
        },
      },
    ],
    inputSchema: personaInput,
    outputSchema: personaOutput,
    creditCost: 5,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["pdf", "md", "txt", "json"],
    promptTemplate: (i: z.infer<typeof personaInput>) => buildLegacyToolPrompt("customer-persona-builder", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof personaOutput>>(r),
  },
  "background-remover": {
    id: "background-remover",
    metadata: {
      name: "AI Background Remover",
      description: "Image background removal is temporarily unavailable.",
      category: "Productivity",
      icon: "🖼️",
      tagline: "Fast cleanup for product visuals and creative assets.",
      estimatedTimeSeconds: 20,
      outputType: "image",
      tags: ["Visual Cleanup", "Creative Ops", "Productivity"],
      featured: false,
      trending: false,
      availability: "coming_soon",
      visibility: "internal",
      disabledReason: "Coming soon",
    },
    fields: [{ name: "imageName", label: "Image Upload", type: "file", helperText: "Upload a product, portrait, or social asset.", required: true }],
    examples: [{ title: "Product cutout", description: "Prepare ecommerce product shots for cleaner landing pages and ads." }],
    presets: [],
    inputSchema: bgInput,
    outputSchema: bgOutput,
    creditCost: 4,
    usageClass: "standard",
    aiModel: "llama-3.1-8b-instant",
    exportFormats: ["png"],
    promptTemplate: () => "",
    outputFormatter: () => ({ status: "coming_soon", message: "Background remover is coming soon." }),
  },
  "landing-page-copy-generator": {
    id: "landing-page-copy-generator",
    metadata: {
      name: "AI Landing Page Copy Generator",
      description: "Conversion-first landing page copy system.",
      category: "Copywriting",
      icon: "🚀",
      tagline: "From positioning brief to polished page sections in one run.",
      estimatedTimeSeconds: 65,
      outputType: "landing-page",
      tags: ["Landing Pages", "Conversion", "SaaS", "Messaging"],
      featured: true,
      trending: true,
      availability: "active",
      visibility: "public",
    },
    fields: [
      { name: "productName", label: "Product Name", type: "text", placeholder: "ZenPilot CRM", helperText: "Use the final product or offer name shown on the page.", required: true },
      { name: "targetAudience", label: "Target Audience", type: "text", placeholder: "Freelance consultants", helperText: "Be clear about who the page is trying to convert.", required: true },
      { name: "coreProblem", label: "Core Problem", type: "text", placeholder: "Losing leads due to messy follow-up", helperText: "State the painful problem the landing page should anchor on.", required: true },
      { name: "mainBenefit", label: "Main Benefit", type: "text", placeholder: "Close more clients in less time", helperText: "This becomes the primary promise throughout the page.", required: true },
      { name: "tone", label: "Tone", type: "select", helperText: "Set the personality of the landing page voice.", required: true, options: [{ label: "Professional", value: "Professional" }, { label: "Bold", value: "Bold" }, { label: "Friendly", value: "Friendly" }] },
    ],
    examples: [
      { title: "Product launch page", description: "Generate a full hero-to-CTA narrative for a new SaaS offer." },
      { title: "Lead capture page", description: "Create persuasive sections, FAQs, and CTA stacks for conversion-focused landing pages." },
    ],
    presets: [
      {
        label: "SaaS homepage message",
        description: "Conversion-ready copy for a startup software offer.",
        values: {
          productName: "ZenPilot CRM",
          targetAudience: "Freelance consultants",
          coreProblem: "Losing leads due to messy follow-up",
          mainBenefit: "Close more clients in less time",
          tone: "Professional",
        },
      },
      {
        label: "Creator course page",
        description: "Landing page copy for digital products and info offers.",
        values: {
          productName: "LaunchLab Bootcamp",
          targetAudience: "Creators launching their first digital product",
          coreProblem: "Feeling overwhelmed by building and marketing a course",
          mainBenefit: "Launch with a proven system and more confidence",
          tone: "Bold",
        },
      },
    ],
    inputSchema: landingInput,
    outputSchema: landingOutput,
    creditCost: 6,
    usageClass: "heavy",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["md", "pdf", "txt", "json"],
    promptTemplate: (i: z.infer<typeof landingInput>) => buildLegacyToolPrompt("landing-page-copy-generator", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof landingOutput>>(r),
  },
  "browser-rewrite": {
    id: "browser-rewrite",
    metadata: {
      name: "Rewrite Text",
      description: "Rewrite selected content with page-aware context.",
      category: "Browser Tools",
      icon: "✍️",
      tagline: "Page-aware rewriting without leaving your current workflow.",
      estimatedTimeSeconds: 18,
      outputType: "text",
      tags: ["Rewrite", "Browser", "Productivity"],
      trending: false,
      availability: "active",
      visibility: "internal",
    },
    fields: [],
    examples: [{ title: "Rewrite a paragraph", description: "Polish a selected passage while preserving intent and context from the active page." }],
    presets: [],
    inputSchema: browserContextInput,
    outputSchema: browserTextOutput,
    creditCost: 8,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof browserContextInput>) => buildLegacyToolPrompt("browser-rewrite", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof browserTextOutput>>(r),
  },
  "browser-summarize": {
    id: "browser-summarize",
    metadata: {
      name: "Summarize Content",
      description: "Condense selected content into high-signal summaries.",
      category: "Browser Tools",
      icon: "🧾",
      tagline: "Turn long selections into usable briefs and takeaways instantly.",
      estimatedTimeSeconds: 16,
      outputType: "text",
      tags: ["Summaries", "Research", "Browser"],
      trending: true,
      availability: "active",
      visibility: "internal",
    },
    fields: [],
    examples: [{ title: "Executive summary", description: "Condense long-form articles, docs, or webpages into concise actionable notes." }],
    presets: [],
    inputSchema: browserContextInput,
    outputSchema: browserTextOutput,
    creditCost: 7,
    usageClass: "standard",
    aiModel: "llama-3.1-8b-instant",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof browserContextInput>) => buildLegacyToolPrompt("browser-summarize", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof browserTextOutput>>(r),
  },
  "browser-improve-writing": {
    id: "browser-improve-writing",
    metadata: {
      name: "Improve Writing",
      description: "Strengthen tone, structure, and readability instantly.",
      category: "Browser Tools",
      icon: "✨",
      tagline: "Instantly elevate grammar, clarity, and persuasive flow in-context.",
      estimatedTimeSeconds: 18,
      outputType: "text",
      tags: ["Writing", "Editing", "Productivity"],
      featured: false,
      trending: true,
      availability: "active",
      visibility: "internal",
    },
    fields: [],
    examples: [{ title: "Sharpen a draft", description: "Improve readability and polish for emails, documents, and landing copy." }],
    presets: [],
    inputSchema: browserContextInput,
    outputSchema: browserTextOutput,
    creditCost: 8,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof browserContextInput>) => buildLegacyToolPrompt("browser-improve-writing", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof browserTextOutput>>(r),
  },
  "browser-seo-helper": {
    id: "browser-seo-helper",
    metadata: {
      name: "SEO Helper",
      description: "Generate SEO improvements from the current page context.",
      category: "Browser Tools",
      icon: "🔎",
      tagline: "Real-time on-page SEO suggestions from your active browser tab.",
      estimatedTimeSeconds: 25,
      outputType: "text",
      tags: ["SEO", "Browser", "Optimization"],
      featured: false,
      trending: true,
      availability: "active",
      visibility: "internal",
    },
    fields: [],
    examples: [{ title: "On-page audit", description: "Review selected page sections and receive optimization suggestions with context." }],
    presets: [],
    inputSchema: browserContextInput,
    outputSchema: browserSeoOutput,
    creditCost: 10,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof browserContextInput>) => buildLegacyToolPrompt("browser-seo-helper", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof browserSeoOutput>>(r),
  },
  "browser-ad-copy": {
    id: "browser-ad-copy",
    metadata: {
      name: "Ad Copy",
      description: "Create platform-ready ad copy from page content and selections.",
      category: "Browser Tools",
      icon: "📣",
      tagline: "Turn live page context into ad-ready messaging from the browser.",
      estimatedTimeSeconds: 24,
      outputType: "text",
      tags: ["Ads", "Social Media", "Browser"],
      featured: false,
      trending: true,
      availability: "active",
      visibility: "internal",
    },
    fields: [],
    examples: [{ title: "Generate ads from a page", description: "Use the current page copy as source material for new ad angles and creative hooks." }],
    presets: [],
    inputSchema: browserContextInput,
    outputSchema: browserAdCopyOutput,
    creditCost: 12,
    usageClass: "standard",
    aiModel: "llama-3.1-70b-versatile",
    exportFormats: ["txt", "json"],
    promptTemplate: (i: z.infer<typeof browserContextInput>) => buildLegacyToolPrompt("browser-ad-copy", i as Record<string, unknown>),
    outputFormatter: (r) => parseJsonResponse<z.infer<typeof browserAdCopyOutput>>(r),
  },
};

export const getToolDefinition = (toolId: string): ToolDefinition | undefined => toolRegistry[toolId];
export const listToolDefinitions = () => Object.values(toolRegistry);
