var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/use-cases/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__09j-_u2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ncll-b.js")
R.c("server/chunks/ssr/lib_seo_content_ts_0hp2_i8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/lib_utils_ts_0ks3cu5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ku17j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ybk2gh._.js")
R.c("server/chunks/ssr/_0yv-zoj._.js")
R.c("server/chunks/ssr/lib_env_ts_1268yyf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_use-cases_[slug]_page_actions_0tdnkxs.js")
R.m(73229)
module.exports=R.m(73229).exports
