var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/billing/subscription/route.js")
R.c("server/chunks/[root-of-the-server]__03oh4sj._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/_0zh1y.d._.js")
R.c("server/chunks/[root-of-the-server]__00-i9j4._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/lib_supabase_admin_ts_02-3bsq._.js")
R.c("server/chunks/_next-internal_server_app_api_billing_subscription_route_actions_0ev45pg.js")
R.m(35622)
module.exports=R.m(35622).exports
