var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/tool-pricing/route.js")
R.c("server/chunks/[root-of-the-server]__0qj-ks9._.js")
R.c("server/chunks/_0zh1y.d._.js")
R.c("server/chunks/definitions_ts_0z1von.._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/lib_supabase_admin_ts_02-3bsq._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_tool-pricing_route_actions_06qm~bm.js")
R.m(88502)
module.exports=R.m(88502).exports
